version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: mysqlwordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "6969:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: mysqlwordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./albatross:/var/www/html

volumes:
  db_data:
